"""
topScopeGenerator() accepts the parsed BPMN process and generates 
the code string that includes the @process for the for the top level scope 
resumable function of the simulation. In BPMN terms, this is the <bpmn:subProcess> 
node included in the <bpmn:process> node.
"""
function topScopeGenerator(parsed)
    topProcessName = findNextNode(findStartEvent(parsed), parsed).name # First node after the start event (in most cases a subProcess)

    codeStr = 
"""
begin   
    @info "\$(@__MODULE__): Starting the simulation run"
    sim = Simulation()
    @process $(topProcessName)(sim)
    @runPersisted(sim, 1000)
    return ("sim ended \$(now())",sim.monitored)
end

""" 
    return codeStr
end

function topLevelResumableGenerator(parsed)
    topProcess = findNextNode(findStartEvent(parsed), parsed) # First node after the start event (in most cases a subProcess)
    @info "topProcess: $(topProcess.name)"
    codeStr = resumableGenerator(topProcess)
    return codeStr
    
end

function resumableGenerator(process::BPMNExecutor.subProcess)
    @info "start exploring tasks and subProcesses in $(process.name)"
    
    innerCodeStr = ""
    for node in process.subnodes
        if node isa BPMNExecutor.task
            @info "task: $(node.name)"
            innerCodeStr *= taskGenerator(node)
        elseif node isa BPMNExecutor.subProcess
            @info "subProcess: $(node.name)"
            @info "add the to generate subprocess/resumable here"
            innerCodeStr *= 
"""
        begin
            @yield @process $(node.name)
        end
"""
        end
    end
    
    outerCodeStr = 
"""
begin
    @resumable function $(process.name)(sim::Environment)
$innerCodeStr
    end true
end
"""
    return outerCodeStr
end

"""
The getRandVarName() function generates a random variable name of 6 characters. This is used to generate unique variable names.
"""
function getRandVarName()
    return join(rand('a':'z',6))
end

"""
taskGenerator() accepts a task type and generates the code string for that task. The returned code must be included in a @resumable function block
which is generated by the resumableGenerator function. The afgument of the @resumable macro is a function which has sim::Environment as its only 
argument. The code generated by taskGenerator must be included in the body of that function.
"""
function taskGenerator(task::BPMNExecutor.task)
    varname = getRandVarName()
    taskCode = task.taskCode
    codeStr = 
"""
        begin
            $varname = $taskCode
            @yield timeout(sim, $varname)
        end
"""
    return codeStr
end