function topScopeGenerator(parsed)
    topProcess = findNextNode(findStartEvent(parsed), parsed).name # First node after the start event (in most cases a subProcess)

    codeStr = """
    begin   
        @info "\$(@__MODULE__): Starting the simulation run"
        sim = Simulation()
        @process $(topProcess)(sim)
        @runPersisted(sim, 1000)
        return ("sim ended \$(now())",sim.monitored)
    end
    """ 
    return codeStr
end

function resumableGenerator(subProcessName::String)
    codeStr = """
    begin
        @resumable function $subProcessName(sim::Environment)
        #before    
        #inner
        #after
        end true
    end
    """
    return codeStr
end

function findStartEvent(parsed::Array{Any,1})
    for node in parsed
        if node isa startEvent
            return node
        end
    end
    return nothing
end

"""
The getRandVarName() function generates a random variable name of 6 characters. This is used to generate unique variable names.
"""
function getRandVarName()
    return join(rand('a':'z',6))
end

"""
taskGenerator() accepts a task type and generates the code string for that task. The returned code must be included in a @resumable function block
which is generated by the resumableGenerator function. The afgument of the @resumable macro is a function which has sim::Environment as its only 
argument. The code generated by taskGenerator must be included in the body of that function.
"""
function taskGenerator(task::BPMNExecutor.task)
    varname = getRandVarName()
    taskCode = task.taskCode
    codeStr = """
    begin
        $varname = $taskCode
        @yield timeout(sim, $varname)
    end
    """
    return codeStr
end
"""
findNextNode() accepts a node and the parsed BPMN process. It returns the next node in the process flow.
"""
function findNextNode(node::BPMNExecutor.nodeType, parsed::Array{Any,1})
    if node isa BPMNExecutor.startEvent
        nextFlowId = node.outgoing[1]
        nextFlow = filter(x -> x.id == nextFlowId, parsed)[1]
        nextNodeId = nextFlow.targetRef
        nextNode = filter(x -> x.id == nextNodeId, parsed)[1]
        return nextNode
    end
end